Default: &defaults
  database: yos.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: yos_test.sqlite3
  <<: *defaults

Staging:
  database: yos_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: yos_production.sqlite3
  poolsize: 100
  <<: *defaults
